apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-deployment
  labels:
    app: admisssion-controller
spec:
  selector:
    matchLabels:
      app: admisssion-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: admisssion-controller
    spec:
      containers:
      - name: admission-controller 
        image: docker.io/pellepedro/controller:latest
        imagePullPolicy: Always
