apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-deployment
  labels:
    app: admission-controller
spec:
  selector:
    matchLabels:
      app: admission-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      containers:
      - name: admission-controller 
        image: open-grid/admission-controller:0.0.1
        imagePullPolicy: IfNotPresent
