
name: CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Build
        run: |
            mkdir -p bin
            go build -o /bin/manager cmd/main.go